Repository 2023-AlphaProject/iBelieveSurvey_frontend, pull requests merged in 2023-05, with the labels that each got.

#44 feat: common button
  src/App.tsx
  src/components/common/Alert/Alert.stories.tsx
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/StyledButton.tsx
  src/components/common/Button/theme.ts
  src/components/common/Button/types.ts
  src/components/common/index.tsx
  src/constants/COLOR.ts
  src/hooks/index.ts
  src/pages/Test.tsx
  src/styles/index.ts
  src/styles/theme.ts
  src/utils/polymorphic.ts
Labels: ✨ Feature, 🎨 Html&css

#45 12/survey/survey wrapper
  src/components/Card/Card.tsx
  src/components/Card/dummyCards.ts
  src/components/Card/types.ts
  src/components/SurveyCardWrapper/SurveyCardWrapper.tsx
  src/pages/Test.tsx
Labels: ✨ Feature

#51 feat: thumbnailBtn
  public/assets/images/thumbnail-icon.svg
  public/assets/images/thumbnail1.png
  public/assets/images/thumbnail2.png
  src/components/Survey/SurveyCardWrapper/SurveyCardWrapper.tsx
  src/components/Survey/ThumbnailBtn/ThumbnailBtn.tsx
  src/components/Survey/ThumbnailBtn/dummyImgs.ts
  src/pages/Test.tsx
Labels: ✨ Feature, 🎨 Html&css

#53 feat: toggle component
  src/components/Survey/index.tsx
  src/components/common/Toggle/Toggle.tsx
  src/components/common/index.tsx
  src/pages/Test.tsx
Labels: 🎨 Html&css

#52 50/survey detail/tab
  src/components/SurveyDetail/Tab/Tab.tsx
  src/components/SurveyDetail/index.tsx
Labels: 🎨 Html&css

#55 Fix colors
  src/components/Footer/Footer.tsx
  src/components/Navbar/DeskTopNavbar.tsx
  src/components/Navbar/MobileNavbar.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/NavbarStyles.tsx
  src/components/Navbar/index.tsx
  src/components/Navbar/logo-black.svg
  src/constants/COLOR.ts
  src/pages/Privacy.tsx
Labels: 🔨 Refactor

#56 Refactor snackbar
  src/hooks/index.ts
  src/hooks/useSnackBar.ts
  src/hooks/useWindowSize.ts
  src/pages/NotFound.tsx
  src/pages/Test.tsx
  src/types/windowSizeType.ts
Labels: 🔨 Refactor

#59 Loading component
  package.json
  public/assets/images/loading.png
  src/components/common/Loading/LoadingComponent.tsx
  src/components/common/Spinner/Spinner.tsx
  src/components/common/index.tsx
  src/pages/Home.tsx
  yarn.lock
Labels: 🎨 Html&css

#54 feat: gifticon cardview component
  public/assets/images/starbucks.jpg
  src/components/Gifticon/CardView/CardView.tsx
  src/components/Gifticon/CardView/dummyCards.ts
  src/components/Gifticon/CardView/types.ts
  src/pages/Test.tsx
Labels: 🎨 Html&css

#66 feat: textarea, input
  package.json
  public/index.html
  src/components/Navbar/DeskTopNavbar.tsx
  src/components/common/Blur/Blur.tsx
  src/components/common/Input/Input.tsx
  src/components/common/TextArea/TextArea.tsx
  src/components/common/index.tsx
  src/hooks/useInput.ts
  src/layouts/Layout.tsx
  src/pages/Survey/New.tsx
  src/pages/Survey/NewSurvey.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#65 64/survey detail/layout
  public/assets/images/human.svg
  src/components/SurveyDetail/Thumbnail/Thumbnail.tsx
  src/pages/Survey/SurveyDetail.tsx
Labels: 🎨 Html&css

#63 14/survey detail/banner
  src/components/Navbar/DeskTopNavbar.tsx
  src/components/Navbar/MobileNavbar.tsx
  src/components/SurveyDetail/Banner/Banner.tsx
  src/components/SurveyDetail/index.tsx
  src/layouts/Layout.tsx
  src/pages/Survey/Survey.tsx
  src/pages/Survey/SurveyDetail.tsx
  src/states/stateBanner.tsx
Labels: ✨ Feature, 🎨 Html&css

#75 feat: [survey-new] step progress bar
  src/App.tsx
  src/components/Survey/New/StepProgress/StepProgress.tsx
  src/components/Survey/New/index.tsx
  src/components/Survey/index.tsx
  src/pages/Survey/NewSurvey.tsx
  src/pages/Survey/NewSurveyForm.tsx
  src/pages/Survey/NewSurveyGift.tsx
  src/styles/index.ts
  src/styles/theme.ts
Labels: ✨ Feature, 🎨 Html&css
