Repository 2023-AlphaProject/iBelieveSurvey_frontend, pull requests merged in 2023-06, with the labels that each got.

#62 61/survey/layout
  src/components/Survey/Card/Card.tsx
  src/components/Survey/NewSurveyBtn/NewSurveyBtn.tsx
  src/components/Survey/SurveyCardWrapper/SurveyCardWrapper.tsx
  src/components/common/Sidebar/Sidebar.tsx
  src/layouts/Layout.tsx
  src/pages/Survey/Survey.tsx
  src/pages/Survey/SurveyDetail.tsx
  src/pages/Survey/SurveySearch.tsx
Labels: 🎨 Html&css

#79 77/gifticon payment/layout
  src/components/Gifticon/Selector/Selector.tsx
  src/pages/Survey/NewSurveyGift.tsx
Labels: 🎨 Html&css

#92 refactor: thumbnail Btn 반응형 적용
  src/components/Gifticon/CardView/CardView.tsx
  src/components/Survey/ThumbnailBtn/ThumbnailBtn.tsx
  src/pages/Survey/NewSurveyGifts.tsx
Labels: 🎨 Html&css

#93 chore: Api/react query config
  package.json
  src/App.tsx
  src/apis/surveysAPI.ts
  src/components/Gifticon/CategoryBox/CategoryBox.tsx
  src/components/Survey/Card/Card.tsx
  src/components/Survey/Card/types.ts
  src/components/Survey/SurveyCardWrapper/SurveyCardWrapper.tsx
  src/config/api.ts
  src/config/quertClients.ts
  src/constants/BASEURL.ts
  src/constants/QUERY_KEYS.ts
  src/hooks/queries/surveys/index.ts
  src/hooks/queries/surveys/useSurveyListQuery.ts
  src/pages/Survey/NewSurvey.tsx
  src/pages/Survey/Survey.tsx
  src/types/surveyType.ts
  yarn.lock
Labels: ✨ Feature, 📬 API

#96 survey-form : survey.js 적용
  package.json
  src/components/Survey/New/Form/SurveyCreator.tsx
  src/components/Survey/New/StepProgress/StepProgress.tsx
  src/components/Survey/New/index.tsx
  src/components/Survey/index.tsx
  src/constants/SURVEY_DEFAULT_JSON.ts
  src/pages/Home.tsx
  src/pages/Survey/New.tsx
  src/pages/Survey/New/NewSurvey.tsx
  src/pages/Survey/New/NewSurveyForm.tsx
  src/pages/Survey/New/NewSurveyGiftItem.tsx
  src/pages/Survey/New/NewSurveyGifts.tsx
  src/pages/Survey/New/NewSurveyPayment.tsx
  src/pages/index.tsx
  src/styles/GlobalStyles.ts
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#97 feat: survey payment page layout
  src/components/Survey/New/Form/SurveyCreator.tsx
  src/components/Survey/New/Payment/BasketItem.tsx
  src/components/Survey/New/Payment/GIftsBasket.tsx
  src/components/Survey/New/Payment/Payment.tsx
  src/components/Survey/New/Payment/PaymentCaution.tsx
  src/components/Survey/New/Payment/RecommendedGifts.tsx
  src/components/Survey/New/Payment/RecommendedItem.tsx
  src/components/Survey/New/StepProgress/StepProgress.tsx
  src/components/Survey/New/index.tsx
  src/components/Survey/index.tsx
  src/components/common/Button/StyledButton.tsx
  src/pages/Survey/New/NewSurvey.tsx
  src/pages/Survey/New/NewSurveyPayment.tsx
Labels: ✨ Feature, 🎨 Html&css

#99 67/survey/category list for searching
  src/components/Survey/SurveySearch/SearchContainer.tsx
  src/components/Survey/index.tsx
  src/constants/COLOR.ts
  src/pages/Survey/SurveySearch.tsx
Labels: ✨ Feature, 🎨 Html&css

#101 100/surqvey/survey card data binding
  src/components/Survey/Card/Card.tsx
Labels: ✨ Feature, 📬 API

#107 deploy: 0615 2350
  src/App.tsx
  src/components/Survey/Card/Card.tsx
  src/components/Survey/New/Form/SurveyCreator.tsx
  src/components/Survey/New/Payment/BasketItem.tsx
  src/components/Survey/New/Payment/GIftsBasket.tsx
  src/components/Survey/New/Payment/Payment.tsx
  src/components/Survey/New/Payment/PaymentCaution.tsx
  src/components/Survey/New/Payment/RecommendedGifts.tsx
  src/components/Survey/New/Payment/RecommendedItem.tsx
  src/components/Survey/New/StepProgress/StepProgress.tsx
  src/components/Survey/New/index.tsx
  src/components/Survey/SurveySearch/SearchContainer.tsx
  src/components/Survey/index.tsx
  src/components/common/Button/StyledButton.tsx
  src/constants/COLOR.ts
  src/pages/Survey/New/NewSurvey.tsx
  src/pages/Survey/New/NewSurveyPayment.tsx
  src/pages/Survey/Survey.tsx
  src/pages/Survey/SurveySearch.tsx
Labels: 🌏 Deploy

#108 Api/survey/get
  src/components/Survey/Card/Card.tsx
  src/components/SurveyDetail/Thumbnail/Thumbnail.tsx
  src/hooks/queries/survey/useSurveyQuery.ts
  src/hooks/useDate.ts
  src/pages/Survey/SurveyDetail.tsx
  src/types/surveyType.ts
Labels: 📬 API

#114 feat: Api/survey/update
  package.json
  public/assets/images/add-button.png
  src/apis/participantAPI.ts
  src/apis/surveysAPI.ts
  src/apis/templatesAPI.ts
  src/components/Gifticon/CardView/CardView.tsx
  src/components/Gifticon/CardView/dummyCards.ts
  src/components/Gifticon/CardView/types.ts
  src/components/Gifticon/CategoryBox/CategoryBox.tsx
  src/components/Gifticon/Selector/Selector.tsx
  src/components/Gifticon/Sidebar/Sidebar.tsx
  src/components/Navbar/DeskTopNavbar.tsx
  src/components/Navbar/Navbar.tsx
  src/components/SignUp/SignUpComponent.tsx
  src/components/SignUp/UserInfoContainer.tsx
  src/components/Survey/New/Form/SurveyCreator.tsx
  src/components/Survey/New/Payment/AddItem.tsx
  src/components/Survey/New/Payment/BasketItem.tsx
  src/components/Survey/New/Payment/GIftsBasket.tsx
  src/components/Survey/New/Payment/Payment.tsx
  src/components/Survey/New/index.tsx
  src/components/Survey/SurveyCardWrapper/SurveyCardWrapper.tsx
  src/components/Survey/index.tsx
  src/constants/QUERY_KEYS.ts
  src/hooks/queries/auth/useUserUpdate.ts
  src/hooks/queries/participant/useAddParticipant.ts
  src/hooks/queries/survey/index.ts
  src/hooks/queries/survey/useSurveyQuery.ts
  src/hooks/queries/surveys/index.ts
  src/hooks/queries/surveys/useUpdateSurvey.ts
  src/hooks/queries/templates/useTemplateListQuery.ts
  src/hooks/queries/templates/useTemplateQuery.ts
  src/hooks/useBasket.ts
  src/pages/KakaoAuth.tsx
  src/pages/Survey/New.tsx
  src/pages/Survey/New/NewSurveyGiftItem.tsx
  src/pages/Survey/New/NewSurveyGifts.tsx
  src/pages/Survey/New/NewSurveyPayment.tsx
  src/pages/Survey/New/SurveySubmit.tsx
  src/pages/Survey/NewSurvey.tsx
  src/pages/Survey/NewSurveyForm.tsx
  src/pages/Survey/NewSurveyGift.tsx
  src/pages/Survey/NewSurveyGifticons.tsx
  src/pages/Survey/Survey.tsx
  src/pages/Survey/SurveyDetail.tsx
  src/states/stateBanner.tsx
  src/states/stateBasket.tsx
  src/types/giftType.ts
  src/types/index.ts
  yarn.lock
Labels: 📬 API

#115 2/api/kakao oauth
  src/App.tsx
  src/components/Navbar/DeskTopNavbar.tsx
  src/components/Navbar/MobileNavbar.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/NavbarStyles.tsx
  src/components/SignUp/SignUpComponent.tsx
  src/components/SignUp/UserInfoContainer.tsx
  src/components/SignUp/types.ts
  src/config/api.ts
  src/hooks/queries/auth/useUserUpdate.ts
  src/pages/Home.tsx
  src/pages/KakaoAuth.tsx
  src/states/stateModal.tsx
  src/states/stateUser.tsx
  src/types/userUpdateType.ts
  src/utils/userToken.ts
Labels: ✨ Feature, 📃 Docs, 📬 API

#120 103/survey/survey search
  .eslintrc
  src/App.tsx
  src/apis/surveysAPI.ts
  src/components/Navbar/DeskTopNavbar.tsx
  src/components/Navbar/MobileNavbar.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/NavbarStyles.tsx
  src/components/Survey/SurveyCardWrapper/SurveyCardWrapper.tsx
  src/components/Survey/SurveySearch/SearchContainer.tsx
  src/components/common/Filterbar/Filterbar.tsx
  src/constants/QUERY_KEYS.ts
  src/hooks/queries/surveys/index.ts
  src/hooks/queries/surveys/useSurveyListSearchQuery.ts
  src/pages/MyPage.tsx
  src/pages/Survey/New/NewSurveyGifts.tsx
  src/pages/Survey/NewSurveyGifticons.tsx
  src/pages/Survey/Survey.tsx
  src/pages/Survey/SurveySearch.tsx
  src/styles/GlobalStyles.ts
Labels: ✨ Feature, 📬 API, 🎨 Html&css
